---
# tasks file for bootstrap

- name: Add ansible repo Ubuntu
  apt_repository:
    repo: ppa:ansible/ansible
  when: ansible_distribution == 'Ubuntu'

- name: Add ansible repo Debian 10
  apt_repository:
    repo: ppa:ansible/ansible
    codename: bionic
  when: ansible_distribution == 'Debian'

- name: Install ansible
  apt:
    name: ansible
    state: latest

- name: Set default cfg
  lineinfile:
    path: /etc/ansible/ansible.cfg
    state: present
    regexp: '#roles_path    = /etc/ansible/roles'
    line: 'roles_path    = /etc/ansible/roles'

